run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - typecheck
    - gocritic
    - goimports
    - revive
    - misspell
    - unconvert
    - prealloc
    - nakedret
    - exhaustive
    - makezero
    - wastedassign

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals